# Generated by Django 2.2.1 on 2020-02-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_ticket_go',
            field=models.IntegerField(default=0, verbose_name='Số Vé Đi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_ticket_return',
            field=models.IntegerField(default=0, verbose_name='Số Vé Về'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number_ticket',
            field=models.IntegerField(default=0, verbose_name='Số Vé Mua'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày Tàu Đi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_time_train',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Giờ Đi'),
        ),
    ]
